### PR TITLE
Doesn't try to create only wayland-0 socket.

### LINKED ISSUE #3: Freeze when running alongside Weston
If I run Perceptia and leave it, then I can not launch an instance of Weston. (The system freezes)
If I have already launched Weston in another tty, Perceptia will not launch. (The system freezes)

```
14:15:57.315796 | INFO1 | p:exhibitor      |   45 | perceptia::exhibitor_module              | Starting Exhibitor module
14:15:57.315930 | ERROR | p:wayland        |   50 | qualia::functions                        | One of threads panicked with message 'Creating display socket: Other("Binding \"/run/user/1000/wayland-0\": \"Address already in use\"")'
14:15:57.315962 | ERROR | p:wayland        |   52 | qualia::functions                        | Panic occurred in line 859, file '/checkout/src/libcore/result.rs'
==============================================================================================
Backtrace for thread 'p:wayland':
> backtrace::backtrace::libunwind::trace
> backtrace::backtrace::trace<closure>
> qualia::log::backtrace
> qualia::functions::panic_hook
> perceptia::main::{{closure}}
> std::panicking::rust_panic_with_hook
> std::panicking::begin_panic<collections::string::String>
> std::panicking::begin_panic_fmt
> std::panicking::rust_begin_panic
> core::panicking::panic_fmt
> core::result::unwrap_failed<skylane::defs::SkylaneError>
> core::result::{{impl}}::expect<skylane::sockets::DisplaySocket,skylane::defs::SkylaneError>
> wayland_frontend::engine::{{impl}}::new
> perceptia::wayland_service::{{impl}}::new
> perceptia::wayland_service::{{impl}}::construct
> dharma::event_loop::{{impl}}::start::{{closure}}
> std::panic::{{impl}}::call_once<(),closure>
> std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
> panic_unwind::__rust_maybe_catch_panic
> std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
> std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
> std::thread::{{impl}}::spawn::{{closure}}<closure,()>
> alloc::boxed::{{impl}}::call_box<(),closure>
> alloc::boxed::{{impl}}::call_once<(),()>
> std::sys_common::thread::start_thread
> std::sys::imp::thread::{{impl}}::new::thread_start
> start_thread
> clone
> <unknown>
==============================================================================================
14:15:57.638097 | INFO1 | p:wayland        |   21 | qualia::functions                        | QUIT!
14:15:57.638174 | INFO2 | p:utils          |  266 | device_manager::virtual_terminal         | Setting up virtual terminal '/dev/tty5'
14:15:57.638217 | INFO1 | main             |   90 | perceptia                                | Stopped dispatcher!
14:15:57.638248 | INFO1 | p:exhibitor      |   95 | perceptia::exhibitor_module              | Finalized Exhibitor module
14:15:57.641961 | INFO1 | p:utils          |   56 | device_manager::udev                     | Found keyboard: "/dev/input/event1"
14:15:57.642869 | INFO1 | p:utils          |   56 | device_manager::udev                     | Found mouse: "/dev/input/event16"
14:15:57.644053 | INFO1 | p:utils          |   56 | device_manager::udev                     | Found keyboard: "/dev/input/event0"
14:15:57.644708 | INFO1 | p:utils          |   56 | device_manager::udev                     | Found touchpad: "/dev/input/event13"
14:15:57.645889 | INFO1 | p:utils          |   75 | device_manager::udev                     | Found output device: "/dev/dri/card0"
14:15:57.645913 | INFO1 | p:utils          |   44 | device_manager::output_collector         | OutputCollector: scan device '"/dev/dri/card0"'
14:15:57.646755 | INFO1 | p:utils          |   75 | device_manager::output_collector         | Connector { id: 47, encoder_id: 46, state: connected, type: eDP }
14:15:57.722201 | INFO1 | p:utils          |   75 | device_manager::output_collector         | Connector { id: 56, encoder_id: 55, state: connected, type: HDMIA }
14:15:57.722631 | WARN1 | p:utils          |  142 | device_manager::device_manager           | Device Manager: Failed to create device monitor
14:15:57.722698 | INFO1 | p:utils          |   39 | perceptia::aesthetics_module             | Starting Aesthetics module
```

### PR DESCRIPTION
**Pull request by llde**
This allow perceptia to be started   with weston and others

Fix #3 at least partially. (If you start weston or something else that use wayland-0 socket, this will probably not work in the reverse case. If weston try to use only wayland-0 socket this is a weston issue)

### CODE REVIEW

File: src/wayland_frontend/engine.rs [hunk 1]
```diff
@@ -52,8 +53,26 @@ impl Engine {
...
+            let try_sock = wl::DisplaySocket::new(&partial_socket_path);
+            if let Ok(sock) = try_sock{
+                socket = Some(sock);
+                break;
+            }
+            partial_socket_path.pop();
+        }
+        if let None = socket{
+            log_warn3!("wayland engine ERROR: cannot open a socket in the 0-9 range");
+            std::process::exit(1);
```
Comment (darkelement) [inline src/wayland_frontend/engine.rs]: Better panic here. This will allow other threads exit cleanly (this doesn't always work for some reason but that's another issue).

File: src/wayland_frontend/engine.rs [hunk 2]
```diff
@@ -52,8 +53,26 @@ impl Engine {
...
+        }
+        else{
+            log_warn1!("socket created at {:?}", partial_socket_path)
```
Comment (darkelement) [inline src/wayland_frontend/engine.rs]: Actually log_info1. log_warn is for cases when something went wrong.

File: src/wayland_frontend/engine.rs [hunk 3]
```diff
@@ -52,8 +53,26 @@ impl Engine {
...
+        }
         Engine {
-            display: wl::DisplaySocket::new_default().expect("Creating display socket"),
+            display: socket.expect("Fatal  ERROR"),
```
Comment (darkelement) [inline src/wayland_frontend/engine.rs]: "Fatal ERROR" is too generic. This message should be informative enough to know immediately what went wrong when you see it in logs.

File: src/wayland_frontend/engine.rs [hunk 4]
```diff
@@ -52,8 +53,26 @@ impl Engine {
     pub fn new(coordinator: Coordinator,
                settings: Settings,
                keyboard_config: KeyboardConfig) -> Self {
+        let mut partial_socket_path = PathBuf::from(std::env::var("XDG_RUNTIME_DIR").unwrap_or("/run/user/1000".to_owned()));
```
Comment (darkelement) [inline src/wayland_frontend/engine.rs]: I forgot to write it in issue, but the order to check should be:
 - default socket
 - wayland-{} sockets
I know you try wayland-0 anyway but what wl::DisplaySocket::new_default does is it's private matter and its behavior may change (theoretically).

I don't like hardcoding the path. I will most probably fail anyway. I would exit if the variable is not set. Specification [1] says "it MUST be created when the user first logs in" so it's bug in desktop environment if it is not set.

[1] https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

File: src/wayland_frontend/engine.rs (hunk 1 above)
Comment (llde) [inline src/wayland_frontend/engine.rs]: I know. But when it was failing on expect internally was panicking. The wayland thread was panicking but the rest of the program still wanted to continue if I read correctly the logs.
IIRC panic is stopped at thread boundary.
I will return to the old panicking way however if you want.

File: src/wayland_frontend/engine.rs (hunk 2 above)
Comment (llde) [inline src/wayland_frontend/engine.rs]: AAAH Damnatio. There is a "debug" log level?

File: src/wayland_frontend/engine.rs (hunk 3 above)
Comment (llde) [inline src/wayland_frontend/engine.rs]: It's too generic it's true but  this case should never be triggered.  I will however change

File: src/wayland_frontend/engine.rs (hunk 4 above)
Comment (llde) [inline src/wayland_frontend/engine.rs]: I will change to panic if XDG_RUNTIME_DIR is  not setted.

**Comment by llde** [comment]
@darkelement  I addressed some of your concerns. However  I'm not able to use cargo fmt on the project
